### ISSUE TITLE
Fails to build on py3.5

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/kitchen#10]
Cf: http://koji.fedoraproject.org/koji/taskinfo?taskID=11792374

**Comment by pypingou** [comment]
I found that ``MAXFD`` has been removed in py 3.5: http://bugs.python.org/issue10838#msg240240

**Comment by pypingou** [comment]
We could re-define ``MAXFD`` to what is it in ``kitchen2/kitchen/pycompat27/subprocess/_subprocess.py``:
````
try:
    MAXFD = os.sysconf("SC_OPEN_MAX")
except:
    MAXFD = 256
````

**Comment by ralphbean** [comment]
:+1: works for me.
